# Generated by Django 3.1 on 2020-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': "today's requests",
                'ordering': ['created_at'],
            },
        ),
    ]
